### ISSUE TITLE
Problem matcher for VBCC

### ISSUE THREAD

**Issue by tehKaiN** [prb28/vscode-amiga-vbcc-example#1]
In tasks.json you can define a problem matcher for build task to make it parse VBCC's errors. When I was still using VBCC I came up with something like this:

``` json
"problemMatcher": {
	"owner": "cpp",
	"fileLocation": "absolute",
	"pattern": {
		"regexp": "^([a-z]*) ([0-9]*) in line ([0-9]*) of \\\"(.*)\\\": (.*)$",
		"severity": 1,
		"line": 3,
		"file": 4,
		"message": 5
	}
},
```

It's not great, but good enough. Perhaps it could enhance your sample project, so I thought I'd share. ;)

**Comment by prb28** [comment]
Yes, it's great!
Thank you I'll add it in the next release.
