### ISSUE TITLE
Includes

### ISSUE THREAD

**Issue by ouya99** [prb28/vscode-amiga-vbcc-example#5]
Hi,

i am new to building for the amiga, and do not know where to get the right include dirs / files

Say I have a file using

#include <proto/exec.h>
#include <proto/dos.h>

how to find correct headers? In the past I setup vbcc manually (including vasm/vlink) and i had to dig deep into NDK3.9 folder structure to get some references to those headers, but it was a mess and I figured out, that they didnt work well with all samples, because header structure changed over time.

in bin/targets i found include/lib for all targets. Should this be enough? How can i link to correct headers files? Thanks !

**Comment by ouya99** [comment]
So i copied 

https://www.dropbox.com/s/2moala3whqvttd1/NDK39.lha?dl=1

into the bin/targets/"TARGET"/include dir and it seems to work for a very basic sample (Helloworld)

but once it uses more libs (intuition etc) i get errors like

Error 21: hello.o (CODE+0x7c): Reference to undefined symbol _OpenWindowTags.
Error 21: hello.o (CODE+0x9e): Reference to undefined symbol _GfxBase.

So i copied the libs from NDK3.9 into the  bin/targets/"TARGET"/lib but it does not change

**Comment by ouya99** [comment]
I read this: http://sun.hasenbraten.de/vbcc/docs/vbcc_11.html to know about which libs i should link to and tried several of those. -lamiga worked!

and modified the Makefile to link with  -lamiga also and it worked. 
"$(VLINK) -bamigahunk -x -Bstatic -Cvbcc -lamiga ........."

Maybe this process of finding a solution to run amigaOs programs can be helpful

**Comment by prb28** [comment]
Great ! Certainly it may help others.
If someone is starting the C programming, one word about how it works:
The .h files are headers they help the compiler to know what is in the libraries. The compiler generates object .o files. After, the linker will tie it with the libraries (it looks for symbols inside the library corresponding to the header file). At the end you have an executable or library ready for work.
